name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Позволяет запускать сборку кнопкой вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Настройка JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Выдача прав на gradlew
        run: chmod +x gradlew

      - name: Сборка APK
        run: ./gradlew assembleDebug

      - name: Загрузка готового APK в артефакты
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          
